//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceStudent_Console_Consumer.ServiceReferenceStudent {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Student", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceStudent_TeamServices_Azure")]
    [System.SerializableAttribute()]
    public partial class Student : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KlasseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Klasse {
            get {
                return this.KlasseField;
            }
            set {
                if ((object.ReferenceEquals(this.KlasseField, value) != true)) {
                    this.KlasseField = value;
                    this.RaisePropertyChanged("Klasse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceStudent.IServiceStudent")]
    public interface IServiceStudent {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceStudent/GetAllStudents", ReplyAction="http://tempuri.org/IServiceStudent/GetAllStudentsResponse")]
        WcfServiceStudent_Console_Consumer.ServiceReferenceStudent.Student[] GetAllStudents();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceStudent/GetAllStudents", ReplyAction="http://tempuri.org/IServiceStudent/GetAllStudentsResponse")]
        System.Threading.Tasks.Task<WcfServiceStudent_Console_Consumer.ServiceReferenceStudent.Student[]> GetAllStudentsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceStudent/GetStudentById", ReplyAction="http://tempuri.org/IServiceStudent/GetStudentByIdResponse")]
        WcfServiceStudent_Console_Consumer.ServiceReferenceStudent.Student GetStudentById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceStudent/GetStudentById", ReplyAction="http://tempuri.org/IServiceStudent/GetStudentByIdResponse")]
        System.Threading.Tasks.Task<WcfServiceStudent_Console_Consumer.ServiceReferenceStudent.Student> GetStudentByIdAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceStudentChannel : WcfServiceStudent_Console_Consumer.ServiceReferenceStudent.IServiceStudent, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceStudentClient : System.ServiceModel.ClientBase<WcfServiceStudent_Console_Consumer.ServiceReferenceStudent.IServiceStudent>, WcfServiceStudent_Console_Consumer.ServiceReferenceStudent.IServiceStudent {
        
        public ServiceStudentClient() {
        }
        
        public ServiceStudentClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceStudentClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceStudentClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceStudentClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WcfServiceStudent_Console_Consumer.ServiceReferenceStudent.Student[] GetAllStudents() {
            return base.Channel.GetAllStudents();
        }
        
        public System.Threading.Tasks.Task<WcfServiceStudent_Console_Consumer.ServiceReferenceStudent.Student[]> GetAllStudentsAsync() {
            return base.Channel.GetAllStudentsAsync();
        }
        
        public WcfServiceStudent_Console_Consumer.ServiceReferenceStudent.Student GetStudentById(int id) {
            return base.Channel.GetStudentById(id);
        }
        
        public System.Threading.Tasks.Task<WcfServiceStudent_Console_Consumer.ServiceReferenceStudent.Student> GetStudentByIdAsync(int id) {
            return base.Channel.GetStudentByIdAsync(id);
        }
    }
}
